# Generated by Django 5.0.4 on 2026-09-01 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, help_text='E.164-ish format, e.g. +919876543210 (see serializers.extract_local_number).', max_length=13, unique=True, verbose_name='mobile number')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='phoneotp',
            name='accounts_ph_phone_06a9a6_idx',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('registration', 'Registration')], default='login', max_length=12),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['phone', 'purpose', 'is_used', '-created_at'], name='accounts_ph_phone_b8ff7e_idx'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
