# Generated by Django 5.0.4 on 2026-09-01 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_phoneotp_purpose_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(db_index=True, help_text='E.164-ish format, e.g. +919876543210 (see serializers.extract_local_number).', max_length=13, unique=True, verbose_name='mobile number')),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('specialization', models.CharField(choices=[('ac', 'AC'), ('refrigerator', 'Refrigerator'), ('washing-machine', 'Washing Machine'), ('microwave', 'Microwave')], max_length=20)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'technician',
                'verbose_name_plural': 'technicians',
                'ordering': ['-joining_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('technician', 'Technician'), ('admin', 'Admin')], db_index=True, default='customer', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
            },
        ),
    ]
