# Generated by Django 5.0.4 on 2026-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_technician_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='specialization',
            field=models.CharField(max_length=60),
        ),
    ]
