# Generated by Django 5.0.4 on 2026-09-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
            ],
            options={
                'verbose_name': 'contact submission',
                'verbose_name_plural': 'contact submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='bookings_co_created_524246_idx')],
            },
        ),
    ]
