# Generated by Django 5.0.4 on 2026-09-03 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_technician_login'),
        ('bookings', '0006_seed_service_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('assigned', 'Job assigned'), ('status_update', 'Status update')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_notifications', to='bookings.booking')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.technicianprofile')),
            ],
            options={
                'verbose_name': 'technician notification',
                'verbose_name_plural': 'technician notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
