# Generated by Django 5.0.4 on 2026-09-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_techniciannotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The technician's commission for this job. Blank until an admin sets one.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_paid',
            field=models.BooleanField(default=False, help_text='Whether commission_amount has actually been paid out to the technician.'),
        ),
        migrations.AlterField(
            model_name='techniciannotification',
            name='type',
            field=models.CharField(choices=[('assigned', 'Job assigned'), ('status_update', 'Status update'), ('commission_updated', 'Commission update')], max_length=20),
        ),
    ]
