# Generated by Django 5.0.4 on 2026-09-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_commission_amount_booking_commission_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianCommission',
            fields=[
            ],
            options={
                'verbose_name': 'technician commission',
                'verbose_name_plural': 'technician commissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.booking',),
        ),
    ]
