# Generated by Django 5.0.4 on 2026-09-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_technician_login'),
        ('bookings', '0009_techniciancommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_created', 'Booking created'), ('technician_assigned', 'Technician assigned'), ('booking_accepted', 'Booking accepted'), ('technician_on_the_way', 'Technician on the way'), ('service_started', 'Service started'), ('service_completed', 'Service completed'), ('booking_cancelled', 'Booking cancelled')], max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifications', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'customer notification',
                'verbose_name_plural': 'customer notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
