"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-egtjbc_n4771$l5^99k4_cc#a0k7x-tktmb(d*1k(330-p93mx',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    # unfold (and the contrib apps it ships for nicer list filters/forms)
    # must be registered before django.contrib.admin — it replaces the
    # built-in admin's templates rather than running alongside them.
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'bookings',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# MySQL/MariaDB, matching the local `urbancool` database created via
# phpMyAdmin (XAMPP's MariaDB by default — root, no password, port 3306).
# Every value below is overridable via .env, the same pattern every other
# setting in this file follows, so a teammate's differently-configured local
# MySQL (or a real production one later) never needs a code change here.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'urbancool'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            # Without this, MariaDB silently truncates/coerces bad data
            # (e.g. a too-long string) instead of raising an error — Django
            # itself warns (mysql.W002) if this isn't set.
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media (user-uploaded files — currently just Booking's attached complaint
# photos, see bookings/models.py's BookingImage). Served by Django itself
# only in DEBUG (config/urls.py appends the static() helper for that) — a
# real deployment serves MEDIA_ROOT through the webserver/object storage
# instead, never through Django.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # No DEFAULT_THROTTLE_CLASSES here deliberately — that would apply
    # AnonRateThrottle to every view project-wide (including bookings' own
    # health check), and it needs a rate for the 'anon' scope that nothing
    # else uses. accounts/views.py and bookings/views.py opt their
    # unauthenticated views in individually via @throttle_classes, scoped to
    # the rates below.
    'DEFAULT_THROTTLE_RATES': {
        'otp_send': '5/min',
        'otp_verify': '10/min',
        'contact_submit': '5/min',
    },
}


# CORS (django-cors-headers) — allow the Vite dev server to call this API.
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
).split(',')

CORS_ALLOW_CREDENTIALS = True

# The customer profile/address/logout/change-mobile endpoints (accounts app)
# are the first *authenticated* state-changing requests in this project —
# DRF's SessionAuthentication only enforces CSRF once request.user is
# authenticated, so the anonymous OTP endpoints never needed this. Without
# the frontend's origin listed here, Django's CSRF check rejects even a
# request carrying a correct X-CSRFToken header, since the request's Origin
# (the Vite dev server) differs from the cookie's own origin (this API).
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
).split(',')


# Console logging for the accounts app — with no LOGGING config, Django
# falls back to Python's root logger, which has no handler and silently
# drops anything below WARNING. Without this, accounts/sms.py's dev-only
# "here's the OTP code" log (INFO level, see its own comment on why that's
# safe) would never actually reach a developer's console.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# OTP auth (accounts app) — all overridable so a deployment can tune them
# without a code change. See accounts/constants.py for where these are read.
OTP_LENGTH = int(os.environ.get('OTP_LENGTH', '6'))
OTP_TTL_SECONDS = int(os.environ.get('OTP_TTL_SECONDS', '300'))
OTP_RESEND_COOLDOWN_SECONDS = int(os.environ.get('OTP_RESEND_COOLDOWN_SECONDS', '45'))
OTP_MAX_ATTEMPTS = int(os.environ.get('OTP_MAX_ATTEMPTS', '5'))
SIGNUP_TOKEN_TTL_SECONDS = int(os.environ.get('SIGNUP_TOKEN_TTL_SECONDS', '600'))


# django-unfold — admin theme
# https://unfoldadmin.com/docs/configuration/settings/
#
# No hand-rolled SIDEBAR.navigation here on purpose: bookings/models.py is
# still empty (no admin-registered models yet), so a hardcoded nav would
# either dangle or need upkeep every time a model is added/removed. Unfold's
# default sidebar already auto-lists every registered model grouped by app,
# which is what we want until there's a reason to curate it.
UNFOLD = {
    'SITE_TITLE': 'Urban Cool Admin',
    'SITE_HEADER': 'Urban Cool',
    'SITE_SYMBOL': 'build',  # Material Symbols icon shown next to the site header
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
}
